### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by hiroaki-ogawa** [qiujiali/lattice_rnn#3]
Hi,
Thank you so much for opening your code.!

Could you share the example data of lattice file and target file? I can't figure out the data type of the 'child_2_parent'.

**Comment by qiujiali** [comment]
I just added an example in this [PR](https://github.com/qiujiali/lattice_rnn/pull/4) with an original HTK lattice and the corresponding processed lattice stored via numpy. `child_2_parent` is a dictionary with keys in ints and values in dictionaries as described in the README file. Hopefully, with this example, you can better understand the description.

**Comment by hiroaki-ogawa** [comment]
Thank you so much for the data and your quick response!
